syntax on

"Color Settings ---
set background=dark
colorscheme solarized

set backspace=2
set nowrap
set ai
set nocp
set ruler

set mouse=a

set tabstop=4
set expandtab
set shiftwidth=4
set shiftround
set showmatch
set smarttab
set softtabstop=4

"autocmd Syntax python set tabstop=4 expandtab shiftwidth=4 shiftround showmatch smarttab softtabstop=4
"autocmd Syntax py set tabstop=4 expandtab shiftwidth=4 shiftround showmatch smarttab softtabstop=4


"Setup eclim"
set nocompatible
filetype plugin on

"<f7> for spell check
nn <f7> :setlocal spell! spelllang=en_us<CR>

"<f1> and <f2> for traversing buffers
nnoremap <f1> :bp<CR>
nnoremap <f2> :bn<CR>

"<F5> to toggle paste mode (great for python copy-paste)
nnoremap <f5> :set paste!<CR>
