## Get shared aliases
if [ -f ~/.bash_aliases ]; then
    source ~/.bash_aliases
fi

## Local Aliases
if [ -f ~/.bash_local_aliases ]; then
    source ~/.bash_local_aliases
fi

# Get profile settings
source ~/.zprofile

# Enable advanced auto-complete
autoload -U compinit
compinit

# enable arrow keys with autocomplete
zstyle ':completion:*' menu select

# fill aliases
#setopt completealiases

# Key bindings
bindkey "\e[1~" beginning-of-line # Home
bindkey "\e[4~" end-of-line # End
bindkey "\e[5~" beginning-of-history # PageUp
bindkey "\e[6~" end-of-history # PageDown
bindkey "\e[2~" quoted-insert # Ins
bindkey "\e[3~" delete-char # Del
bindkey "\e[5C" forward-word
bindkey "\eOc" emacs-forward-word
bindkey "\e[5D" backward-word
bindkey "\eOd" emacs-backward-word
bindkey "\e\e[C" forward-word
bindkey "\e\e[D" backward-word
bindkey "\e[Z" reverse-menu-complete # Shift+Tab
# for rxvt
bindkey "\e[7~" beginning-of-line # Home
bindkey "\e[8~" end-of-line # End

bindkey "^[[A" history-beginning-search-backward
bindkey "^[[B" history-beginning-search-forward

# Load pre-made prompts
#autoload -U promptinit
#promptinit

# Setup oh-my-zsh
ZSH=$HOME/.oh-my-zsh

ZSH_THEME="clean"
CASE_SENSITIVE="true"
DISABLE_AUTO_UPDATE="true"
plugins=(git vi-mode archlinux)

source $ZSH/oh-my-zsh.sh

set -o vi

unset sharehistory
