#Color alias
alias rm='rm -I'
alias mv='mv -i'
alias cp='cp -i'

alias ls='ls --color=auto'
alias grep='grep --colour=auto'

alias wget='wget -c'

#todo.txt alias
alias t="todo.sh"
alias ta="todo.sh add"
alias tls="todo.sh ls"
alias tl="todo.sh ls"
alias td="todo.sh do"
alias tr="todo.sh do"

#git alias
alias g="git"
alias ga="git add"
alias gs="git status"
alias gl="git log"
alias gd="git diff"
